// Command kolibri-locality measures per layer how the locality workloads' expert selections
// concentrate (internal/locality), from the selection files tools/locality/experts.py writes.
// It backs "Expert locality per layer" in docs/real-checkpoint.md.
//
//	kolibri-locality -models Kolibri-1-IQ3_XXS-IQ4_XS-down-imx,Kolibri-1-Q8_0 -md docs/expert-locality.md
//
// For each model (a GGUF file name without .gguf) and workload it reads
// <dir>/<workload>.<model>.experts.npy, writes every layer's measures to
// <dir>/stats-<model>.json, prints a summary line per model and workload and, given -md, writes
// the summary and per-layer tables as Markdown. With two models it also prints, per workload,
// how often both select the same experts for a token in a layer.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"kolibri-llm/internal/locality"
)

// coverageAt are the token counts at which coverage is read out (and at a workload's end).
var coverageAt = []int{1024, 2048, 4096, 8192, 16384, 24576}

// Layer is one layer's measures with the derived concentration figures.
type Layer struct {
	Layer int `json:"layer"`
	locality.Stats
	Top6  float64 `json:"top6_share"`
	Top24 float64 `json:"top24_share"`
	Top96 float64 `json:"top96_share"`
	For50 int     `json:"experts_for_50"`
	For90 int     `json:"experts_for_90"`
	For99 int     `json:"experts_for_99"`
}

func measure(sel locality.Selections, nExpert int) []Layer {
	out := make([]Layer, sel.Layers)
	for l := range out {
		s := locality.Measure(sel.Layer(l), nExpert, coverageAt)
		out[l] = Layer{Layer: l, Stats: s, Top6: s.TopShare(6), Top24: s.TopShare(24), Top96: s.TopShare(96),
			For50: s.ExpertsFor(0.5), For90: s.ExpertsFor(0.9), For99: s.ExpertsFor(0.99)}
	}
	return out
}

// agreement is the share of (layer, token) pairs for which a and b select the same experts,
// overall and per layer.
func agreement(a, b locality.Selections) (float64, []float64) {
	per := make([]float64, a.Layers)
	same := 0
	for l := range a.Layers {
		la, lb := a.Layer(l), b.Layer(l)
		n := 0
		for t := range la {
			if locality.SameSet(la[t], lb[t]) {
				n++
			}
		}
		per[l] = float64(n) / float64(len(la))
		same += n
	}
	return float64(same) / float64(a.Layers*a.Tokens), per
}

// spread is the mean, minimum and maximum of f over the layers.
func spread(layers []Layer, f func(Layer) float64) (mean, lo, hi float64) {
	lo, hi = f(layers[0]), f(layers[0])
	for _, l := range layers {
		v := f(l)
		mean += v / float64(len(layers))
		lo, hi = min(lo, v), max(hi, v)
	}
	return mean, lo, hi
}

// coverage is a layer's coverage after the first n tokens, -1 if it was not read out there.
func coverage(l Layer, n int) float64 {
	for _, p := range l.Coverage {
		if p.Tokens == n {
			return p.Share
		}
	}
	return -1
}

// points are the coverage read-outs of a workload: the fixed counts it reaches and its end.
func points(layers []Layer) []int {
	var out []int
	for _, p := range layers[0].Coverage {
		out = append(out, p.Tokens)
	}
	return out
}

func pct(v float64) string { return fmt.Sprintf("%.1f%%", 100*v) }

func pctRange(mean, lo, hi float64) string {
	return fmt.Sprintf("%.1f%% (%.1f–%.1f)", 100*mean, 100*lo, 100*hi)
}

func tokensLabel(n int) string {
	if n%1024 == 0 {
		return fmt.Sprintf("%dk", n/1024)
	}
	return fmt.Sprint(n)
}

type result struct {
	model, workload string
	layers          []Layer
}

func (r result) mean(f func(Layer) float64) float64 {
	m, _, _ := spread(r.layers, f)
	return m
}

func summary(r result) string {
	end := r.layers[0].Tokens
	return fmt.Sprintf("%s %s: %d tokens, %d layers; mean over layers: coverage at the end %s, never selected %s, "+
		"top-24 share %s, %.0f experts for 90%%, normalized entropy %.3f, Gini %.3f, median stack distance %.0f",
		r.model, r.workload, end, len(r.layers),
		pct(r.mean(func(l Layer) float64 { return coverage(l, end) })),
		pctRange(spread(r.layers, func(l Layer) float64 { return l.NeverSelected })),
		pct(r.mean(func(l Layer) float64 { return l.Top24 })),
		r.mean(func(l Layer) float64 { return float64(l.For90) }),
		r.mean(func(l Layer) float64 { return l.NormEntropy }),
		r.mean(func(l Layer) float64 { return l.Gini }),
		r.mean(func(l Layer) float64 { return float64(l.StackDistance.Median) }))
}

func writeMarkdown(w io.Writer, command string, results []result, agree map[string]string) {
	fmt.Fprintf(w, "# Expert locality per layer\n\n")
	fmt.Fprintf(w, "Generated by `%s` from the selection files of `tools/locality/experts.py`; do not edit by hand. "+
		"The measures are defined in `internal/locality` and explained in "+
		"[real-checkpoint.md](real-checkpoint.md#expert-locality-per-layer).\n\n", command)
	fmt.Fprintf(w, "## Summary\n\nMean over the layers; ranges are the minimum and maximum over the layers.\n\n")
	fmt.Fprintf(w, "| Model | Workload | Tokens | Coverage 1k | Coverage 8k | Coverage at the end | Never selected | "+
		"Top-24 share | Experts for 90%% | Normalized entropy | Gini | Token distance median | "+
		"Stack distance median / p90 |\n")
	fmt.Fprintf(w, "|---|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|\n")
	for _, r := range results {
		end := r.layers[0].Tokens
		cov := func(n int) string { return pct(r.mean(func(l Layer) float64 { return coverage(l, n) })) }
		fmt.Fprintf(w, "| %s | %s | %d | %s | %s | %s | %s | %s | %.0f | %.3f | %.3f | %.0f | %.0f / %.0f |\n",
			r.model, r.workload, end, cov(1024), cov(8192), cov(end),
			pctRange(spread(r.layers, func(l Layer) float64 { return l.NeverSelected })),
			pct(r.mean(func(l Layer) float64 { return l.Top24 })),
			r.mean(func(l Layer) float64 { return float64(l.For90) }),
			r.mean(func(l Layer) float64 { return l.NormEntropy }),
			r.mean(func(l Layer) float64 { return l.Gini }),
			r.mean(func(l Layer) float64 { return float64(l.TokenDistance.Median) }),
			r.mean(func(l Layer) float64 { return float64(l.StackDistance.Median) }),
			r.mean(func(l Layer) float64 { return float64(l.StackDistance.P90) }))
	}
	if len(agree) > 0 {
		fmt.Fprintf(w, "\nThe same expert set in both models, as a share of all (layer, token) pairs:\n\n")
		listed := map[string]bool{}
		for _, r := range results {
			if a, ok := agree[r.workload]; ok && !listed[r.workload] {
				fmt.Fprintf(w, "- %s: %s\n", r.workload, a)
				listed[r.workload] = true
			}
		}
	}
	for _, r := range results {
		pts := points(r.layers)
		fmt.Fprintf(w, "\n## %s, %s\n\n| Layer |", r.model, r.workload)
		for _, p := range pts {
			fmt.Fprintf(w, " Coverage %s |", tokensLabel(p))
		}
		fmt.Fprintf(w, " Never selected | Max share | Median count | Top-6 | Top-24 | Top-96 | "+
			"Experts for 50/90/99%% | Entropy (bits) | Normalized entropy | Gini | Cold share | "+
			"Token distance median/p90/p99 | Stack distance median/p90/p99 |\n|--:|%s%s\n",
			strings.Repeat("--:|", len(pts)), strings.Repeat("--:|", 13))
		for _, l := range r.layers {
			fmt.Fprintf(w, "| %d |", l.Layer)
			for _, p := range pts {
				fmt.Fprintf(w, " %s |", pct(coverage(l, p)))
			}
			fmt.Fprintf(w, " %s | %s | %.1f | %s | %s | %s | %d / %d / %d | %.2f | %.3f | %.3f | %s | "+
				"%d / %d / %d | %d / %d / %d |\n",
				pct(l.NeverSelected), pct(l.MaxShare), l.MedianCount, pct(l.Top6), pct(l.Top24), pct(l.Top96),
				l.For50, l.For90, l.For99, l.Entropy, l.NormEntropy, l.Gini, pct(l.ColdShare),
				l.TokenDistance.Median, l.TokenDistance.P90, l.TokenDistance.P99,
				l.StackDistance.Median, l.StackDistance.P90, l.StackDistance.P99)
		}
	}
}

func main() {
	home, _ := os.UserHomeDir()
	dir := flag.String("dir", filepath.Join(home, "models", "eval", "locality"), "selection files and stats output")
	models := flag.String("models", "", "comma-separated GGUF names without .gguf")
	workloads := flag.String("workloads", "coding,research,hr,medtech", "comma-separated workloads")
	nExpert := flag.Int("experts", 384, "routed experts per layer")
	md := flag.String("md", "", "write the Markdown report here")
	flag.Parse()
	if *models == "" {
		flag.Usage()
		os.Exit(2)
	}
	ms, ws := strings.Split(*models, ","), strings.Split(*workloads, ",")
	sels := map[string]locality.Selections{}
	var results []result
	for _, m := range ms {
		stats := map[string][]Layer{}
		for _, wl := range ws {
			sel, err := locality.ReadNPYFile(filepath.Join(*dir, fmt.Sprintf("%s.%s.experts.npy", wl, m)))
			if err != nil {
				log.Fatal(err)
			}
			sels[m+"/"+wl] = sel
			r := result{m, wl, measure(sel, *nExpert)}
			stats[wl] = r.layers
			results = append(results, r)
			fmt.Println(summary(r))
		}
		b, err := json.MarshalIndent(stats, "", " ")
		if err != nil {
			log.Fatal(err)
		}
		out := filepath.Join(*dir, "stats-"+m+".json")
		if err := os.WriteFile(out, append(b, '\n'), 0o644); err != nil {
			log.Fatal(err)
		}
		fmt.Println("wrote", out)
	}
	agree := map[string]string{}
	if len(ms) == 2 {
		for _, wl := range ws {
			a, b := sels[ms[0]+"/"+wl], sels[ms[1]+"/"+wl]
			if a.Layers != b.Layers || a.Tokens != b.Tokens || a.K != b.K {
				log.Fatalf("%s: the %s and %s selections differ in shape", wl, ms[0], ms[1])
			}
			total, per := agreement(a, b)
			agree[wl] = fmt.Sprintf("%s (per layer %s to %s)", pct(total), pct(slices.Min(per)), pct(slices.Max(per)))
			fmt.Printf("INFO %s: %s and %s select the same %d experts in %s\n", wl, ms[0], ms[1], a.K, agree[wl])
		}
	}
	if *md != "" {
		f, err := os.Create(*md)
		if err != nil {
			log.Fatal(err)
		}
		writeMarkdown(f, "go run ./cmd/kolibri-locality -models "+*models+" -md "+*md, results, agree)
		if err := f.Close(); err != nil {
			log.Fatal(err)
		}
		fmt.Println("wrote", *md)
	}
}
